import { Routes } from '@angular/router';

export const COMPONENTS_SHOWCASE_ROUTES: Routes = [
  { path: '', redirectTo: 'button', pathMatch: 'full' },
  { path: 'button', loadComponent: () => import('./components/button.component').then(m => m.ButtonSectionComponent) },
  { path: 'input', loadComponent: () => import('./components/input.component').then(m => m.InputSectionComponent) },
  { path: 'textarea', loadComponent: () => import('./components/textarea.component').then(m => m.TextareaSectionComponent) },
  { path: 'select', loadComponent: () => import('./components/select.component').then(m => m.SelectSectionComponent) },
  { path: 'checkbox', loadComponent: () => import('./components/checkbox.component').then(m => m.CheckboxSectionComponent) },
  { path: 'radio', loadComponent: () => import('./components/radio.component').then(m => m.RadioSectionComponent) },
  { path: 'switch', loadComponent: () => import('./components/switch.component').then(m => m.SwitchSectionComponent) },
  { path: 'card', loadComponent: () => import('./components/card.component').then(m => m.CardSectionComponent) },
  { path: 'toolbar', loadComponent: () => import('./components/toolbar.component').then(m => m.ToolbarSectionComponent) },
  { path: 'sidenav', loadComponent: () => import('./components/sidenav.component').then(m => m.SidenavSectionComponent) },
  { path: 'menu', loadComponent: () => import('./components/menu.component').then(m => m.MenuSectionComponent) },
  { path: 'dialog', loadComponent: () => import('./components/dialog.component').then(m => m.DialogSectionComponent) },
  { path: 'snackbar', loadComponent: () => import('./components/snackbar.component').then(m => m.SnackbarSectionComponent) },
  { path: 'table', loadComponent: () => import('./components/table.component').then(m => m.TableSectionComponent) },
  { path: 'autocomplete', loadComponent: () => import('./pages/autocomplete/autocomplete.component').then(m => m.PageAutocompleteComponent) },
  { path: 'badge', loadComponent: () => import('./pages/badge/badge.component').then(m => m.PageBadgeComponent) },
  { path: 'bottomsheet', loadComponent: () => import('./pages/bottomsheet/bottomsheet.component').then(m => m.PageBottomSheetComponent) },
  { path: 'buttontoggle', loadComponent: () => import('./pages/buttontoggle/buttontoggle.component').then(m => m.PageButtonToggleComponent) },
  { path: 'chips', loadComponent: () => import('./pages/chips/chips.component').then(m => m.PageChipsComponent) },
  { path: 'datepicker', loadComponent: () => import('./pages/datepicker/datepicker.component').then(m => m.PageDatepickerComponent) },
  { path: 'divider', loadComponent: () => import('./pages/divider/divider.component').then(m => m.PageDividerComponent) },
  { path: 'expansion', loadComponent: () => import('./pages/expansionpanel/expansionpanel.component').then(m => m.PageExpansionComponent) },
  { path: 'formfield', loadComponent: () => import('./pages/formfield/formfield.component').then(m => m.PageFormFieldComponent) },
  { path: 'gridlist', loadComponent: () => import('./pages/gridlist/gridlist.component').then(m => m.PageGridListComponent) },
  { path: 'icon', loadComponent: () => import('./pages/icon/icon.component').then(m => m.PageIconComponent) },
  { path: 'list', loadComponent: () => import('./pages/list/list.component').then(m => m.PageListComponent) },
  { path: 'paginator', loadComponent: () => import('./pages/paginator/paginator.component').then(m => m.PagePaginatorComponent) },
  { path: 'progressbar', loadComponent: () => import('./pages/progressbar/progressbar.component').then(m => m.PageProgressBarComponent) },
  { path: 'progressspinner', loadComponent: () => import('./pages/progressspinner/progressspinner.component').then(m => m.PageProgressSpinnerComponent) },
  { path: 'slidetoggle', loadComponent: () => import('./pages/slidetoggle/slidetoggle.component').then(m => m.PageSlideToggleComponent) },
  { path: 'slider', loadComponent: () => import('./pages/slider/slider.component').then(m => m.PageSliderComponent) },
  { path: 'sortheader', loadComponent: () => import('./pages/sortheader/sortheader.component').then(m => m.PageSortHeaderComponent) },
  { path: 'stepper', loadComponent: () => import('./pages/stepper/stepper.component').then(m => m.PageStepperComponent) },
  { path: 'tabs', loadComponent: () => import('./pages/tabs/tabs.component').then(m => m.PageTabsComponent) },
  { path: 'timepicker', loadComponent: () => import('./pages/timepicker/timepicker.component').then(m => m.PageTimepickerComponent) },
  { path: 'tooltip', loadComponent: () => import('./pages/tooltip/tooltip.component').then(m => m.PageTooltipComponent) },
  { path: 'tree', loadComponent: () => import('./pages/tree/tree.component').then(m => m.PageTreeComponent) },
];
